/* The following code was generated by JFlex 1.3.5 on 26/04/18 23.55 */

package compiler;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java_cup.runtime.Symbol;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 26/04/18 23.55 from the specification file
 * <tt>file:/C:/Users/Utente/Documents/Workspace-eclipse/YASPL2_Compiler/lexer.jflex</tt>
 */
public class Lexer implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int STRING = 1;
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\11\7\1\3\1\2\1\0\1\3\1\1\16\7\4\0\1\3\1\0"+
    "\1\42\1\0\1\6\1\0\1\50\1\0\1\52\1\53\1\5\1\44"+
    "\1\56\1\45\1\12\1\4\1\10\11\11\1\57\1\60\1\46\1\43"+
    "\1\47\2\0\1\16\2\6\1\17\1\15\2\6\1\14\11\6\1\22"+
    "\1\20\1\21\6\6\1\0\1\13\2\0\1\6\1\0\1\41\1\37"+
    "\1\6\1\23\1\24\1\25\1\6\1\30\1\26\2\6\1\32\1\6"+
    "\1\31\1\35\2\6\1\40\1\33\1\27\1\36\1\6\1\34\3\6"+
    "\1\54\1\51\1\55\1\0\41\7\2\0\4\6\4\0\1\6\2\0"+
    "\1\7\7\0\1\6\4\0\1\6\5\0\27\6\1\0\37\6\1\0"+
    "\u01ca\6\4\0\14\6\16\0\5\6\7\0\1\6\1\0\1\6\21\0"+
    "\160\7\5\6\1\0\2\6\2\0\4\6\10\0\1\6\1\0\3\6"+
    "\1\0\1\6\1\0\24\6\1\0\123\6\1\0\213\6\1\0\5\7"+
    "\2\0\236\6\11\0\46\6\2\0\1\6\7\0\47\6\7\0\1\6"+
    "\1\0\55\7\1\0\1\7\1\0\2\7\1\0\2\7\1\0\1\7"+
    "\10\0\33\6\5\0\3\6\15\0\5\7\6\0\1\6\4\0\13\7"+
    "\5\0\53\6\37\7\4\0\2\6\1\7\143\6\1\0\1\6\10\7"+
    "\1\0\6\7\2\6\2\7\1\0\4\7\2\6\12\7\3\6\2\0"+
    "\1\6\17\0\1\7\1\6\1\7\36\6\33\7\2\0\131\6\13\7"+
    "\1\6\16\0\12\7\41\6\11\7\2\6\4\0\1\6\5\0\26\6"+
    "\4\7\1\6\11\7\1\6\3\7\1\6\5\7\22\0\31\6\3\7"+
    "\104\0\1\6\1\0\13\6\67\0\33\7\1\0\4\7\66\6\3\7"+
    "\1\6\22\7\1\6\7\7\12\6\2\7\2\0\12\7\1\0\7\6"+
    "\1\0\7\6\1\0\3\7\1\0\10\6\2\0\2\6\2\0\26\6"+
    "\1\0\7\6\1\0\1\6\3\0\4\6\2\0\1\7\1\6\7\7"+
    "\2\0\2\7\2\0\3\7\1\6\10\0\1\7\4\0\2\6\1\0"+
    "\3\6\2\7\2\0\12\7\4\6\7\0\1\6\5\0\3\7\1\0"+
    "\6\6\4\0\2\6\2\0\26\6\1\0\7\6\1\0\2\6\1\0"+
    "\2\6\1\0\2\6\2\0\1\7\1\0\5\7\4\0\2\7\2\0"+
    "\3\7\3\0\1\7\7\0\4\6\1\0\1\6\7\0\14\7\3\6"+
    "\1\7\13\0\3\7\1\0\11\6\1\0\3\6\1\0\26\6\1\0"+
    "\7\6\1\0\2\6\1\0\5\6\2\0\1\7\1\6\10\7\1\0"+
    "\3\7\1\0\3\7\2\0\1\6\17\0\2\6\2\7\2\0\12\7"+
    "\1\0\1\6\17\0\3\7\1\0\10\6\2\0\2\6\2\0\26\6"+
    "\1\0\7\6\1\0\2\6\1\0\5\6\2\0\1\7\1\6\7\7"+
    "\2\0\2\7\2\0\3\7\10\0\2\7\4\0\2\6\1\0\3\6"+
    "\2\7\2\0\12\7\1\0\1\6\20\0\1\7\1\6\1\0\6\6"+
    "\3\0\3\6\1\0\4\6\3\0\2\6\1\0\1\6\1\0\2\6"+
    "\3\0\2\6\3\0\3\6\3\0\14\6\4\0\5\7\3\0\3\7"+
    "\1\0\4\7\2\0\1\6\6\0\1\7\16\0\12\7\11\0\1\6"+
    "\7\0\3\7\1\0\10\6\1\0\3\6\1\0\27\6\1\0\12\6"+
    "\1\0\5\6\3\0\1\6\7\7\1\0\3\7\1\0\4\7\7\0"+
    "\2\7\1\0\2\6\6\0\2\6\2\7\2\0\12\7\22\0\2\7"+
    "\1\0\10\6\1\0\3\6\1\0\27\6\1\0\12\6\1\0\5\6"+
    "\2\0\1\7\1\6\7\7\1\0\3\7\1\0\4\7\7\0\2\7"+
    "\7\0\1\6\1\0\2\6\2\7\2\0\12\7\1\0\2\6\17\0"+
    "\2\7\1\0\10\6\1\0\3\6\1\0\51\6\2\0\1\6\7\7"+
    "\1\0\3\7\1\0\4\7\1\6\10\0\1\7\10\0\2\6\2\7"+
    "\2\0\12\7\12\0\6\6\2\0\2\7\1\0\22\6\3\0\30\6"+
    "\1\0\11\6\1\0\1\6\2\0\7\6\3\0\1\7\4\0\6\7"+
    "\1\0\1\7\1\0\10\7\22\0\2\7\15\0\60\6\1\7\2\6"+
    "\7\7\4\0\10\6\10\7\1\0\12\7\47\0\2\6\1\0\1\6"+
    "\2\0\2\6\1\0\1\6\2\0\1\6\6\0\4\6\1\0\7\6"+
    "\1\0\3\6\1\0\1\6\1\0\1\6\2\0\2\6\1\0\4\6"+
    "\1\7\2\6\6\7\1\0\2\7\1\6\2\0\5\6\1\0\1\6"+
    "\1\0\6\7\2\0\12\7\2\0\4\6\40\0\1\6\27\0\2\7"+
    "\6\0\12\7\13\0\1\7\1\0\1\7\1\0\1\7\4\0\2\7"+
    "\10\6\1\0\44\6\4\0\24\7\1\0\2\7\5\6\13\7\1\0"+
    "\44\7\11\0\1\7\71\0\53\6\24\7\1\6\12\7\6\0\6\6"+
    "\4\7\4\6\3\7\1\6\3\7\2\6\7\7\3\6\4\7\15\6"+
    "\14\7\1\6\17\7\2\0\46\6\1\0\1\6\5\0\1\6\2\0"+
    "\53\6\1\0\u014d\6\1\0\4\6\2\0\7\6\1\0\1\6\1\0"+
    "\4\6\2\0\51\6\1\0\4\6\2\0\41\6\1\0\4\6\2\0"+
    "\7\6\1\0\1\6\1\0\4\6\2\0\17\6\1\0\71\6\1\0"+
    "\4\6\2\0\103\6\2\0\3\7\40\0\20\6\20\0\125\6\14\0"+
    "\u026c\6\2\0\21\6\1\0\32\6\5\0\113\6\3\0\3\6\17\0"+
    "\15\6\1\0\4\6\3\7\13\0\22\6\3\7\13\0\22\6\2\7"+
    "\14\0\15\6\1\0\3\6\1\0\2\7\14\0\64\6\40\7\3\0"+
    "\1\6\3\0\2\6\1\7\2\0\12\7\41\0\3\7\2\0\12\7"+
    "\6\0\130\6\10\0\51\6\1\7\1\6\5\0\106\6\12\0\35\6"+
    "\3\0\14\7\4\0\14\7\12\0\12\7\36\6\2\0\5\6\13\0"+
    "\54\6\4\0\21\7\7\6\2\7\6\0\12\7\46\0\27\6\5\7"+
    "\4\0\65\6\12\7\1\0\35\7\2\0\13\7\6\0\12\7\15\0"+
    "\1\6\130\0\5\7\57\6\21\7\7\6\4\0\12\7\21\0\11\7"+
    "\14\0\3\7\36\6\15\7\2\6\12\7\54\6\16\7\14\0\44\6"+
    "\24\7\10\0\12\7\3\0\3\6\12\7\44\6\122\0\3\7\1\0"+
    "\25\7\4\6\1\7\4\6\3\7\2\6\11\0\300\6\47\7\25\0"+
    "\4\7\u0116\6\2\0\6\6\2\0\46\6\2\0\6\6\2\0\10\6"+
    "\1\0\1\6\1\0\1\6\1\0\1\6\1\0\37\6\2\0\65\6"+
    "\1\0\7\6\1\0\1\6\3\0\3\6\1\0\7\6\3\0\4\6"+
    "\2\0\6\6\4\0\15\6\5\0\3\6\1\0\7\6\16\0\5\7"+
    "\32\0\5\7\20\0\2\6\23\0\1\6\13\0\5\7\5\0\6\7"+
    "\1\0\1\6\15\0\1\6\20\0\15\6\3\0\33\6\25\0\15\7"+
    "\4\0\1\7\3\0\14\7\21\0\1\6\4\0\1\6\2\0\12\6"+
    "\1\0\1\6\3\0\5\6\6\0\1\6\1\0\1\6\1\0\1\6"+
    "\1\0\4\6\1\0\13\6\2\0\4\6\5\0\5\6\4\0\1\6"+
    "\21\0\51\6\u0a77\0\57\6\1\0\57\6\1\0\205\6\6\0\4\6"+
    "\3\7\2\6\14\0\46\6\1\0\1\6\5\0\1\6\2\0\70\6"+
    "\7\0\1\6\17\0\1\7\27\6\11\0\7\6\1\0\7\6\1\0"+
    "\7\6\1\0\7\6\1\0\7\6\1\0\7\6\1\0\7\6\1\0"+
    "\7\6\1\0\40\7\57\0\1\6\u01d5\0\3\6\31\0\11\6\6\7"+
    "\1\0\5\6\2\0\5\6\4\0\126\6\2\0\2\7\2\0\3\6"+
    "\1\0\132\6\1\0\4\6\5\0\51\6\3\0\136\6\21\0\33\6"+
    "\65\0\20\6\u0200\0\u19b6\6\112\0\u51cd\6\63\0\u048d\6\103\0\56\6"+
    "\2\0\u010d\6\3\0\20\6\12\7\2\6\24\0\57\6\1\7\4\0"+
    "\12\7\1\0\31\6\7\0\1\7\120\6\2\7\45\0\11\6\2\0"+
    "\147\6\2\0\4\6\1\0\4\6\14\0\13\6\115\0\12\6\1\7"+
    "\3\6\1\7\4\6\1\7\27\6\5\7\20\0\1\6\7\0\64\6"+
    "\14\0\2\7\62\6\21\7\13\0\12\7\6\0\22\7\6\6\3\0"+
    "\1\6\4\0\12\7\34\6\10\7\2\0\27\6\15\7\14\0\35\6"+
    "\3\0\4\7\57\6\16\7\16\0\1\6\12\7\46\0\51\6\16\7"+
    "\11\0\3\6\1\7\10\6\2\7\2\0\12\7\6\0\27\6\3\0"+
    "\1\6\1\7\4\0\60\6\1\7\1\6\3\7\2\6\2\7\5\6"+
    "\2\7\1\6\1\7\1\6\30\0\3\6\2\0\13\6\5\7\2\0"+
    "\3\6\2\7\12\0\6\6\2\0\6\6\2\0\6\6\11\0\7\6"+
    "\1\0\7\6\221\0\43\6\10\7\1\0\2\7\2\0\12\7\6\0"+
    "\u2ba4\6\14\0\27\6\4\0\61\6\u2104\0\u016e\6\2\0\152\6\46\0"+
    "\7\6\14\0\5\6\5\0\1\6\1\7\12\6\1\0\15\6\1\0"+
    "\5\6\1\0\1\6\1\0\2\6\1\0\2\6\1\0\154\6\41\0"+
    "\u016b\6\22\0\100\6\2\0\66\6\50\0\15\6\3\0\20\7\20\0"+
    "\7\7\14\0\2\6\30\0\3\6\31\0\1\6\6\0\5\6\1\0"+
    "\207\6\2\0\1\7\4\0\1\6\13\0\12\7\7\0\32\6\4\0"+
    "\1\6\1\0\32\6\13\0\131\6\3\0\6\6\2\0\6\6\2\0"+
    "\6\6\2\0\3\6\3\0\2\6\3\0\2\6\22\0\3\7\4\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    49,    98,   147,    98,   196,    98,   245,   294,   343, 
      392,   441,   490,   539,   588,   637,   686,   735,   784,   833, 
       98,   882,    98,   931,   980,  1029,  1078,  1127,    98,    98, 
       98,    98,    98,    98,    98,  1176,  1225,    98,  1274,  1323, 
     1372,  1421,  1470,  1519,  1568,  1617,  1666,   245,  1715,  1764, 
     1813,  1862,  1911,  1960,    98,    98,    98,    98,    98,    98, 
       98,    98,    98,    98,    98,  2009,  2058,  1372,  2107,  2156, 
      245,  2205,  2254,  2303,   245,  2352,  2401,   245,  2450,  2499, 
     2548,   245,  2597,  2646,   245,  2695,   245,   245,  2744,   245, 
      245,  2793,   245,   245,   245
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\3\1\4\2\5\1\6\1\7\1\10\1\3\1\11"+
    "\1\12\2\3\1\13\3\10\1\14\2\10\1\15\1\16"+
    "\1\17\1\20\1\21\1\10\1\22\2\10\1\23\2\10"+
    "\1\24\2\10\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\2\3\10\44\1\45\26\44\1\46\16\44"+
    "\63\0\1\5\62\0\1\47\1\50\61\0\4\10\2\0"+
    "\26\10\31\0\1\51\56\0\2\12\1\51\54\0\4\10"+
    "\2\0\1\10\1\52\24\10\25\0\4\10\2\0\5\10"+
    "\1\53\20\10\25\0\4\10\2\0\10\10\1\54\10\10"+
    "\1\55\4\10\25\0\4\10\2\0\16\10\1\56\7\10"+
    "\25\0\4\10\2\0\25\10\1\57\25\0\4\10\2\0"+
    "\11\10\1\60\3\10\1\61\10\10\25\0\4\10\2\0"+
    "\14\10\1\62\7\10\1\63\1\10\25\0\4\10\2\0"+
    "\21\10\1\64\4\10\25\0\4\10\2\0\14\10\1\65"+
    "\11\10\25\0\4\10\2\0\21\10\1\66\4\10\62\0"+
    "\1\67\64\0\1\70\54\0\1\71\1\0\1\72\56\0"+
    "\1\73\65\0\1\74\61\0\1\75\7\0\1\44\2\0"+
    "\10\44\1\0\26\44\1\0\16\44\27\0\1\76\1\0"+
    "\1\77\6\0\1\100\1\0\1\101\16\0\1\47\1\4"+
    "\1\5\56\47\5\102\1\103\53\102\10\0\2\104\55\0"+
    "\4\10\2\0\2\10\1\105\23\10\25\0\4\10\2\0"+
    "\2\10\1\106\23\10\25\0\4\10\2\0\11\10\1\107"+
    "\14\10\25\0\4\10\2\0\22\10\1\110\3\10\25\0"+
    "\4\10\2\0\17\10\1\111\6\10\25\0\4\10\2\0"+
    "\16\10\1\112\7\10\25\0\4\10\2\0\13\10\1\113"+
    "\12\10\25\0\4\10\2\0\10\10\1\114\15\10\25\0"+
    "\4\10\2\0\22\10\1\115\3\10\25\0\4\10\2\0"+
    "\13\10\1\116\12\10\25\0\4\10\2\0\12\10\1\117"+
    "\13\10\25\0\4\10\2\0\21\10\1\120\4\10\17\0"+
    "\5\102\1\121\53\102\4\0\1\5\1\103\61\0\4\10"+
    "\2\0\3\10\1\122\22\10\25\0\4\10\2\0\6\10"+
    "\1\123\17\10\25\0\4\10\2\0\23\10\1\124\2\10"+
    "\25\0\4\10\2\0\10\10\1\125\15\10\25\0\4\10"+
    "\2\0\17\10\1\126\6\10\25\0\4\10\2\0\15\10"+
    "\1\127\10\10\25\0\4\10\2\0\10\10\1\130\15\10"+
    "\25\0\4\10\2\0\16\10\1\131\7\10\25\0\4\10"+
    "\2\0\16\10\1\132\7\10\17\0\4\102\1\5\1\121"+
    "\53\102\6\0\4\10\2\0\5\10\1\133\20\10\25\0"+
    "\4\10\2\0\16\10\1\134\7\10\25\0\4\10\2\0"+
    "\10\10\1\135\15\10\25\0\4\10\2\0\10\10\1\136"+
    "\15\10\25\0\4\10\2\0\10\10\1\137\15\10\17\0";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  0,  9,  1,  9,  1,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  9,  1,  9,  1,  1,  1,  1,  1,  9,  9,  9,  9, 
     9,  9,  9,  1,  1,  9,  1,  0,  0,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 
     9,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
	
    private StringBuffer string;
    private ComplexSymbolFactory symbolFactory;
    private int csline, cscolumn;
    
    public Lexer(ComplexSymbolFactory factory, java.io.InputStream stream) {
		this(stream);
        symbolFactory = factory;
        string = new StringBuffer();
    }
    
	public Lexer(ComplexSymbolFactory factory, java.io.Reader reader) {
		this(reader);
        symbolFactory = factory;
        string = new StringBuffer();
    }

    public Symbol symbol(String name, int code) {
		return symbolFactory.newSymbol(name, code,
				new Location(yyline + 1, yycolumn + 1, yychar), // -yylength()
				new Location(yyline + 1, yycolumn + yylength(), yychar + yylength()));
    }
    
    public Symbol symbol(String name, int code, String lexem) {
		return symbolFactory.newSymbol(name, code, 
				new Location(yyline + 1, yycolumn + 1, yychar), 
				new Location(yyline + 1,yycolumn + yylength(), yychar + yylength()), lexem);
    }
    
    protected void emit_warning(String message) {
    	System.out.println("scanner warning: " + message + " at : 2 " + 
    			(yyline + 1) + " " + (yycolumn + 1) + " " + yychar);
    }
    
    protected void emit_error(String message) {
    	System.out.println("scanner error: " + message + " at : 2" + 
    			(yyline + 1) + " " + (yycolumn + 1) + " " + yychar);
    }
    


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[2842];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2260) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      yychar+= yy_markedPos_l-yy_startRead;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 20: 
          {  string.setLength(0); yybegin(STRING);  }
        case 96: break;
        case 3: 
        case 4: 
          {   }
        case 97: break;
        case 38: 
          {   }
        case 98: break;
        case 93: 
          {  return symbolFactory.newSymbol("WHILE", sym.WHILE);  }
        case 99: break;
        case 92: 
          {  return symbolFactory.newSymbol("FALSE", sym.FALSE);  }
        case 100: break;
        case 90: 
          {  return symbolFactory.newSymbol("START", sym.START);  }
        case 101: break;
        case 32: 
          {  return symbolFactory.newSymbol("COMMA", sym.COMMA);  }
        case 102: break;
        case 31: 
          {  return symbolFactory.newSymbol("RGPAR", sym.RGPAR);  }
        case 103: break;
        case 30: 
          {  return symbolFactory.newSymbol("LGPAR", sym.LGPAR);  }
        case 104: break;
        case 23: 
          {  return symbolFactory.newSymbol("MINUS", sym.MINUS);  }
        case 105: break;
        case 6: 
          {  return symbolFactory.newSymbol("TIMES", sym.TIMES);  }
        case 106: break;
        case 33: 
          {  return symbolFactory.newSymbol("COLON", sym.COLON);  }
        case 107: break;
        case 55: 
          {  return symbolFactory.newSymbol("WRITE", sym.WRITE);  }
        case 108: break;
        case 77: 
          {  return symbolFactory.newSymbol("NOT", sym.NOT);  }
        case 109: break;
        case 74: 
          {  return symbolFactory.newSymbol("INT", sym.INT);  }
        case 110: break;
        case 70: 
          {  return symbolFactory.newSymbol("DEF", sym.DEF);  }
        case 111: break;
        case 5: 
          {  return symbolFactory.newSymbol("DIV", sym.DIV);  }
        case 112: break;
        case 59: 
          {  return symbolFactory.newSymbol("AND", sym.AND);  }
        case 113: break;
        case 94: 
          {  return symbolFactory.newSymbol("DOUBLE", sym.DOUBLE);  }
        case 114: break;
        case 21: 
          {  return symbolFactory.newSymbol("ASSIGN", sym.ASSIGN);  }
        case 115: break;
        case 7: 
        case 10: 
        case 11: 
        case 12: 
        case 13: 
        case 14: 
        case 15: 
        case 16: 
        case 17: 
        case 18: 
        case 19: 
        case 41: 
        case 42: 
        case 43: 
        case 45: 
        case 46: 
        case 48: 
        case 49: 
        case 50: 
        case 51: 
        case 52: 
        case 53: 
        case 68: 
        case 69: 
        case 71: 
        case 72: 
        case 73: 
        case 75: 
        case 76: 
        case 78: 
        case 79: 
        case 82: 
        case 83: 
        case 85: 
        case 88: 
        case 91: 
          {  return symbolFactory.newSymbol("NAME", sym.NAME, yytext());  }
        case 116: break;
        case 64: 
          {  string.append('\"');  }
        case 117: break;
        case 25: 
          {  return symbolFactory.newSymbol("GT", sym.GT);  }
        case 118: break;
        case 24: 
          {  return symbolFactory.newSymbol("LT", sym.LT);  }
        case 119: break;
        case 2: 
        case 26: 
        case 27: 
          {  emit_warning("Unrecognized character '" + yytext() + "' -- ignored");  }
        case 120: break;
        case 36: 
          {  string.append('\\');  }
        case 121: break;
        case 44: 
          {  return symbolFactory.newSymbol("DO", sym.DO);  }
        case 122: break;
        case 47: 
          {  return symbolFactory.newSymbol("IF", sym.IF);  }
        case 123: break;
        case 54: 
          {  return symbolFactory.newSymbol("EQ", sym.EQ);  }
        case 124: break;
        case 56: 
          {  return symbolFactory.newSymbol("LE", sym.LE);  }
        case 125: break;
        case 58: 
          {  return symbolFactory.newSymbol("GE", sym.GE);  }
        case 126: break;
        case 60: 
          {  return symbolFactory.newSymbol("OR", sym.OR);  }
        case 127: break;
        case 61: 
          {  string.append('\t');  }
        case 128: break;
        case 62: 
          {  string.append('\n');  }
        case 129: break;
        case 63: 
          {  string.append('\r');  }
        case 130: break;
        case 35: 
          {  string.append(yytext());  }
        case 131: break;
        case 37: 
          {  yybegin(YYINITIAL);
                          return symbolFactory.newSymbol("STRING_CONST", sym.STRING_CONST, 
                          		string.toString());  }
        case 132: break;
        case 89: 
          {  return symbolFactory.newSymbol("BOOL", sym.BOOL);  }
        case 133: break;
        case 87: 
          {  return symbolFactory.newSymbol("TRUE", sym.TRUE);  }
        case 134: break;
        case 86: 
          {  return symbolFactory.newSymbol("THEN", sym.THEN);  }
        case 135: break;
        case 84: 
          {  return symbolFactory.newSymbol("ELSE", sym.ELSE);  }
        case 136: break;
        case 81: 
          {  return symbolFactory.newSymbol("HEAD", sym.HEAD);  }
        case 137: break;
        case 29: 
          {  return symbolFactory.newSymbol("RPAR", sym.RPAR);  }
        case 138: break;
        case 28: 
          {  return symbolFactory.newSymbol("LPAR", sym.LPAR);  }
        case 139: break;
        case 22: 
          {  return symbolFactory.newSymbol("PLUS", sym.PLUS);  }
        case 140: break;
        case 34: 
          {  return symbolFactory.newSymbol("SEMI", sym.SEMI);  }
        case 141: break;
        case 57: 
          {  return symbolFactory.newSymbol("READ", sym.READ);  }
        case 142: break;
        case 67: 
          {  return symbolFactory.newSymbol("DOUBLE_CONST", sym.DOUBLE_CONST, 
								Double.parseDouble(yytext()));  }
        case 143: break;
        case 8: 
        case 9: 
          {  return symbolFactory.newSymbol("INT_CONST", sym.INT_CONST, 
								Integer.parseInt(yytext()));  }
        case 144: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              {     return symbolFactory.newSymbol("EOF",sym.EOF);
 }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
